openapi: 3.0.2
info:
  title: 学生情報を取得するAPI
  description: |-
    <b>学生情報を取得するAPIの仕様</b><br>
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1/
tags:
  - name: student
    description: 学生関連API

paths:
  /students/:
    get:
      tags:
        - student
      summary: ユーザー詳細表示API（メッセージ詳細内）
      description: |
        全ての学生の情報を取得
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentsProlilesGetResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBadRequest"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseInternalServerError"
  /students/{student_id}/:
    get:
      tags:
        - student
      summary: ユーザー詳細表示API（メッセージ詳細内）
      description: |
        指定した学生の情報を取得
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentProfileGetResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBadRequest"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseInternalServerError"
components:
  schemas:
    StudentsProlilesGetResponse:
      type: object
      properties:
        students:
          type: array
          items:
            $ref: "#/components/schemas/StudentProfileGetResponse"
          description: 全ての学生の情報
    StudentProfileGetResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: 学生ID
        name:
          type: string
          example: 山田太郎
          description: 学生の名前
        age:
          type: integer
          example: 16
          description: 年齢
        class:
          type: integer
          example: 1
          description: クラス番号
    ErrorResponseBadRequest:
      title: ErrorResponseBadRequest
      type: object
      description: BadRequest時のエラーレスポンス
      properties:
        message:
          type: string
          description: エラーメッセージサンプル
          example: リクエストが不正です
      required:
        - code
        - message
    ErrorResponseInternalServerError:
      title: ErrorResponseInternalServerError
      type: object
      description: サーバーエラー時のエラーレスポンス
      properties:
        message:
          type: string
          description: エラーメッセージサンプル
          example: サーバーエラーが発生しました
      required:
        - message
